version: '3.8'

services:
  mikrotik-bot:
    build: .
    container_name: mikrotik-bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - mikrotik-network

networks:
  mikrotik-network:
    driver: bridge

